export const DEFAULT_HOME_LANGUAGE = 'en'
export const HOME_LANGUAGE_STORAGE_KEY = 'appLanguage'
export const FAV_LANGUAGES_STORAGE_KEY = 'favLanguages'
export const ADVANCEMENT_LEVELS_STORAGE_KEY = 'advancementLevels'
export const STORED_TEXTS_STORAGE_KEY = 'lastTexts'
export const COLOR_THEME_STORAGE_KEY = 'colorTheme'
